# fly.toml app configuration file generated for resumeio-to-pdf on 2023-11-26T20:19:30-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "resumeio-to-pdf"
primary_region = "gru"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
